embedding_model:
  provider: "openai"
  model_name: "text-embedding-ada-002"

retriever:
  top_k: 10 
  search_type: "mmr" 
  fetch_k: 20 
  lambda_mult: 0.5

llm:
  provider: "openai" 
  model_name: "gpt-4o-mini"
  temperature: 0 
  max_output_tokens: 2048